server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/booking/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/transaction/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*" 